# docker-compose.yml for FHIRVINE

services:
  fhirvine:
    build: .
    container_name: fhirvine_app
    ports:
      - "5001:5001"
    volumes:
      - fhirvine_instance:/app/instance
      - fhirvine_migrations:/app/migrations
    environment:
      - FLASK_ENV=${FLASK_ENV:-development}
    env_file:
      - .env
    command: >
      sh -c "flask db upgrade && waitress-serve --host=0.0.0.0 --port=5001 --call 'app:create_app'"
    restart: unless-stopped

volumes:
  fhirvine_instance:
  fhirvine_migrations: